rules = [
"Person(?s), Person(?p), isSisterOf(?s, ?p) -> gender(?s, 'female')",
"Person(?s), Person(?p), isBrotherOf(?s, ?p) -> gender(?s, 'male')",
"Person(?x), Person(?z), isSonOf(?x, ?z) -> gender(?x, 'male')",
"Person(?x), Person(?z), isDaughterOf(?x, ?z) -> gender(?x, 'female')",
"Person(?x), Person(?y), isMotherOf(?x, ?y) -> gender(?x, 'female')",
"Person(?x), Person(?y), isFatherOf(?x, ?y) -> gender(?x, 'male')",
"Person(?x), Person(?y), isWifeOf(?x, ?y) ->  gender(?x, 'female')",
"Person(?x), Person(?y), isHusbandOf(?x, ?y) ->  gender(?x, 'male')",
"Person(?x), Person(?y), isUncleOf(?x, ?y) -> gender(?x, 'male')",
"Person(?x), Person(?y), isAuntOf(?x, ?y) -> gender(?x, 'female')",
"Person(?x), Person(?y), isNieceOf(?x, ?y) ->  gender(?x, 'female')",
"Person(?x), Person(?y), isNephewOf(?x, ?y) ->  gender(?x, 'male')",

"Person(?x), Person(?y), gender(?x, 'male'), isParentOf(?y, ?x) -> isSonOf(?x, ?y)",
"Person(?x), Person(?y), gender(?x, 'female'), isParentOf(?y, ?x) -> isDaughterOf(?x, ?y)",
"Person(?x), Person(?y), gender(?x, 'male'), isChildOf(?y, ?x) -> isFatherOf(?x, ?y)",
"Person(?x), Person(?y), gender(?x, 'female'), isChildOf(?y, ?x) -> isMotherOf(?x, ?y)",
"Person(?x), Person(?y), gender(?x, 'male'), isSiblingOf(?y, ?x) -> isBrotherOf(?x, ?y)",
"Person(?x), Person(?y), gender(?x, 'female'), isSiblingOf(?y, ?x) -> isSisterOf(?x, ?y)",
"Person(?x), Person(?y), gender(?x, 'male'), isPartnerOf(?y, ?x) -> isHusbandOf(?x, ?y)",
"Person(?x), Person(?y), gender(?x, 'male'), isPartnerOf(?y, ?x) -> isWifeOf(?y, ?x)",
"Person(?x), Person(?y), gender(?x, 'female'), isPartnerOf(?y, ?x) -> isHusbandOf(?y, ?x)",
"Person(?x), Person(?y), gender(?x, 'female'), isPartnerOf(?y, ?x) -> isWifeOf(?x, ?y)",
"Person(?x), gender(?x, 'female'), Person(?y), isNephewOf(?y, ?x) -> isAuntOf(?x, ?y)",
"Person(?x), gender(?x, 'female'), Person(?y), isNieceOf(?y, ?x) -> isAuntOf(?x, ?y)",
"Person(?x), gender(?x, 'male'), Person(?y), isNephewOf(?y, ?x) -> isUncleOf(?x, ?y)",
"Person(?x), gender(?x, 'male'), Person(?y), isNieceOf(?y, ?x) -> isUncleOf(?x, ?y)",
    
"Person(?x), Person(?y),  Person(?z), isSiblingOf(?x, ?z), isChildOf(?z, ?y), gender(?x, 'male') -> isSonOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isChildOf(?x, ?z), isPartnerOf(?z, ?y), gender(?x, 'male') -> isSonOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isSiblingOf(?x, ?z), isChildOf(?z, ?y), gender(?x, 'female') -> isDaughterOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isChildOf(?x, ?z), isPartnerOf(?z, ?y), gender(?x, 'female') -> isDaughterOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isParentOf(?x, ?z), isSiblingOf(?z, ?y), gender(?x, 'male') -> isFatherOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isPartnerOf(?x, ?z), isParentOf(?z, ?y), gender(?z, 'female') -> isFatherOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isPartnerOf(?x, ?z), isParentOf(?z, ?y), gender(?x, 'male') -> isFatherOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isParentOf(?x, ?z), isSiblingOf(?z, ?y), gender(?x, 'female') -> isMotherOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isPartnerOf(?x, ?z), isParentOf(?z, ?y), gender(?z, 'male') -> isMotherOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isPartnerOf(?x, ?z), isParentOf(?z, ?y), gender(?x, 'female') -> isMotherOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isChildOf(?x, ?z), isParentOf(?z, ?y), gender(?x, 'female') -> isSisterOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isParentOf(?x, ?z), isUncleOf(?y, ?z), gender(?x, 'female') -> isSisterOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isParentOf(?x, ?z), isAuntOf(?y, ?z), gender(?x, 'female') -> isSisterOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isChildOf(?x, ?z), isParentOf(?z, ?y), gender(?x, 'male') -> isBrotherOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isParentOf(?x, ?z), isUncleOf(?y, ?z), gender(?x, 'male') -> isBrotherOf(?x, ?y)",
"Person(?x), Person(?y),  Person(?z), isParentOf(?x, ?z), isAuntOf(?y, ?z), gender(?x, 'male') -> isBrotherOf(?x, ?y)",
"Person(?x), Person(?y), Person(?z), isSiblingOf(?x, ?y), isParentOf(?y, ?z), gender(?z, 'female') -> isNieceOf(?z, ?x)",
"Person(?x), Person(?y), Person(?z), isSiblingOf(?x, ?y), isParentOf(?y, ?z), gender(?z, 'male') -> isNephewOf(?z, ?x)",
"Person(?x), Person(?y), Person(?z), isCousinOf(?x, ?y), isParentOf(?z, ?y), gender(?z, 'male') -> isUncleOf(?z, ?x)",
"Person(?x), Person(?y), Person(?z), isCousinOf(?x, ?y), isParentOf(?z, ?y), gender(?z, 'female') -> isAuntOf(?z, ?x)",
"Person(?x), Person(?y), Person(?z), isChildOf(?x, ?z), isUncleOf(?z, ?y) -> isCousinOf(?x, ?y)",
"Person(?x), Person(?y), Person(?z), isChildOf(?x, ?z), isAuntOf(?z, ?y) -> isCousinOf(?x, ?y)",

"Person(?w), Person(?x), Person(?y), Person(?z), isParentOf(?x, ?y), isParentOf(?w, ?z), isSiblingOf(?x, ?w)-> isCousinOf(?z, ?y)",
]